//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 5/21/2015 1:33:24 PM
namespace ToDoTasksList.Models.Repository
{
    
    /// <summary>
    /// There are no comments for ToDoTaskEntities in the schema.
    /// </summary>
    public partial class ToDoTaskEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new ToDoTaskEntities object using the connection string found in the 'ToDoTaskEntities' section of the application configuration file.
        /// </summary>
        public ToDoTaskEntities() : 
                base("name=ToDoTaskEntities", "ToDoTaskEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ToDoTaskEntities object.
        /// </summary>
        public ToDoTaskEntities(string connectionString) : 
                base(connectionString, "ToDoTaskEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ToDoTaskEntities object.
        /// </summary>
        public ToDoTaskEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "ToDoTaskEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Tasks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Task> Tasks
        {
            get
            {
                if ((this._Tasks == null))
                {
                    this._Tasks = base.CreateQuery<Task>("[Tasks]");
                }
                return this._Tasks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Task> _Tasks;
        /// <summary>
        /// There are no comments for OneTwoes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<OneTwo> OneTwoes
        {
            get
            {
                if ((this._OneTwoes == null))
                {
                    this._OneTwoes = base.CreateQuery<OneTwo>("[OneTwoes]");
                }
                return this._OneTwoes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<OneTwo> _OneTwoes;
        /// <summary>
        /// There are no comments for Tasks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToTasks(Task task)
        {
            base.AddObject("Tasks", task);
        }
        /// <summary>
        /// There are no comments for OneTwoes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToOneTwoes(OneTwo oneTwo)
        {
            base.AddObject("OneTwoes", oneTwo);
        }
    }
    /// <summary>
    /// There are no comments for ToDoTaskList.Models.Entity.Task in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TaskID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ToDoTaskList.Models.Entity", Name="Task")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Task : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Task object.
        /// </summary>
        /// <param name="taskID">Initial value of TaskID.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="dateAdded">Initial value of DateAdded.</param>
        /// <param name="isCompleted">Initial value of IsCompleted.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Task CreateTask(int taskID, string description, global::System.DateTime dateAdded, bool isCompleted)
        {
            Task task = new Task();
            task.TaskID = taskID;
            task.Description = description;
            task.DateAdded = dateAdded;
            task.IsCompleted = isCompleted;
            return task;
        }
        /// <summary>
        /// There are no comments for property TaskID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int TaskID
        {
            get
            {
                return this._TaskID;
            }
            set
            {
                this.OnTaskIDChanging(value);
                this.ReportPropertyChanging("TaskID");
                this._TaskID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TaskID");
                this.OnTaskIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _TaskID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTaskIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTaskIDChanged();
        /// <summary>
        /// There are no comments for property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Description;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDescriptionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for property DateAdded in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime DateAdded
        {
            get
            {
                return this._DateAdded;
            }
            set
            {
                this.OnDateAddedChanging(value);
                this.ReportPropertyChanging("DateAdded");
                this._DateAdded = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateAdded");
                this.OnDateAddedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _DateAdded;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDateAddedChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDateAddedChanged();
        /// <summary>
        /// There are no comments for property IsCompleted in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public bool IsCompleted
        {
            get
            {
                return this._IsCompleted;
            }
            set
            {
                this.OnIsCompletedChanging(value);
                this.ReportPropertyChanging("IsCompleted");
                this._IsCompleted = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsCompleted");
                this.OnIsCompletedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private bool _IsCompleted;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIsCompletedChanging(bool value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIsCompletedChanged();
        /// <summary>
        /// There are no comments for property DateCompleted in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> DateCompleted
        {
            get
            {
                return this._DateCompleted;
            }
            set
            {
                this.OnDateCompletedChanging(value);
                this.ReportPropertyChanging("DateCompleted");
                this._DateCompleted = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateCompleted");
                this.OnDateCompletedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _DateCompleted;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDateCompletedChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDateCompletedChanged();
    }
    /// <summary>
    /// There are no comments for ToDoTaskList.Models.Entity.OneTwo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// OneTwoID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ToDoTaskList.Models.Entity", Name="OneTwo")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class OneTwo : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new OneTwo object.
        /// </summary>
        /// <param name="oneTwoID">Initial value of OneTwoID.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static OneTwo CreateOneTwo(int oneTwoID)
        {
            OneTwo oneTwo = new OneTwo();
            oneTwo.OneTwoID = oneTwoID;
            return oneTwo;
        }
        /// <summary>
        /// There are no comments for property OneTwoID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int OneTwoID
        {
            get
            {
                return this._OneTwoID;
            }
            set
            {
                this.OnOneTwoIDChanging(value);
                this.ReportPropertyChanging("OneTwoID");
                this._OneTwoID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("OneTwoID");
                this.OnOneTwoIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _OneTwoID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnOneTwoIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnOneTwoIDChanged();
        /// <summary>
        /// There are no comments for property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Description;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDescriptionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for property RankOrder in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> RankOrder
        {
            get
            {
                return this._RankOrder;
            }
            set
            {
                this.OnRankOrderChanging(value);
                this.ReportPropertyChanging("RankOrder");
                this._RankOrder = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("RankOrder");
                this.OnRankOrderChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _RankOrder;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRankOrderChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRankOrderChanged();
    }
}
